#!/usr/bin/env bash
# Tinkered Tactile image pipeline.
#
#   _tools/tt-image.sh <source-image> <name>   add (or replace) one image
#   _tools/tt-image.sh --manifest              just rebuild the manifest
#
# Writes assets/tinkered-tactile/img/<name>-<width>.{avif,webp} at up to four
# widths (never wider than the source) plus one <name>-<width>.jpg fallback
# (at most 1200px, which is also what social cards get), strips all metadata
# — GPS included — and rebuilds _data/tt_images.yml, which
# {% include tt/picture.html name="<name>" %} reads to build its srcset.
#
# Crop before you run it; this script only resizes and encodes.
# Needs vips (resize, WebP, JPEG) and ffmpeg with libaom-av1 (AVIF). Without
# ffmpeg it still works, the pages just serve WebP.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=assets/tinkered-tactile/img
MANIFEST=_data/tt_images.yml
WIDTHS=(480 800 1200 1600)
FALLBACK_MAX=1200
BG="242 238 228"   # cream, for flattening any transparency

vips_q() { vips "$@" 2> >(grep -v -E 'VIPS-WARNING|^$' >&2); }
widths_of() { ls "$OUT" | sed -n -E "s#^$1-([0-9]+)\\.$2\$#\\1#p" | sort -n; }

build_manifest() {
  local tmp name widths largest fallback
  tmp=$(mktemp)
  {
    echo "# Generated by _tools/tt-image.sh — don't edit by hand."
    echo "# name: { widths: [...], width, height (of the largest), fallback: jpg width, avif }"
    for name in $(ls "$OUT" | sed -n -E 's#^(.+)-[0-9]+\.webp$#\1#p' | sort -u); do
      widths=$(widths_of "$name" webp | paste -sd, - | sed 's/,/, /g')
      largest=$(widths_of "$name" webp | tail -1)
      fallback=$(widths_of "$name" jpg | tail -1)
      avif=false; [ -f "$OUT/$name-$largest.avif" ] && avif=true
      printf '%s: { widths: [%s], width: %s, height: %s, fallback: %s, avif: %s }\n' "$name" "$widths" \
        "$(vipsheader -f width "$OUT/$name-$largest.webp" 2>/dev/null)" \
        "$(vipsheader -f height "$OUT/$name-$largest.webp" 2>/dev/null)" "$fallback" "$avif"
    done
  } > "$tmp"
  mv "$tmp" "$MANIFEST"
  echo "manifest: $(grep -c '^[a-z0-9]' "$MANIFEST") images -> $MANIFEST"
}

if [ "${1:-}" = "--manifest" ]; then build_manifest; exit 0; fi
if [ $# -ne 2 ]; then sed -n '2,16p' "$0" | sed 's/^# \{0,1\}//'; exit 1; fi

src=$1 name=$2
[ -f "$src" ] || { echo "no such file: $src" >&2; exit 1; }
[[ "$name" =~ ^[a-z0-9]+(-[a-z0-9]+)*$ ]] || { echo "name must be kebab-case: $name" >&2; exit 1; }
mkdir -p "$OUT"
rm -f "$OUT/$name"-[0-9]*.{avif,webp,jpg}

srcw=$(vipsheader -f width "$src" 2>/dev/null)
max=$(( srcw < 1600 ? srcw : 1600 ))
sizes=()
for w in "${WIDTHS[@]}"; do [ "$w" -lt "$max" ] && sizes+=("$w"); done
sizes+=("$max")
fallback=${sizes[0]}
for w in "${sizes[@]}"; do [ "$w" -le "$FALLBACK_MAX" ] && fallback=$w; done

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
for w in "${sizes[@]}"; do
  # --height keeps portrait images from being capped by height: width rules.
  vips_q thumbnail "$src" "$work/r.v" "$w" --height 100000 --size down
  vips_q flatten "$work/r.v" "$work/f.png" --background "$BG" 2>/dev/null || vips_q copy "$work/r.v" "$work/f.png"
  vips_q copy "$work/f.png" "$OUT/$name-$w.webp[Q=80,keep=none]"
  if [ "$w" = "$fallback" ]; then
    vips_q copy "$work/f.png" "$OUT/$name-$w.jpg[Q=82,optimize_coding,interlace,keep=none]"
  fi
  if command -v ffmpeg >/dev/null; then
    # -nostdin: otherwise ffmpeg eats the caller's stdin (e.g. a while-read loop)
    ffmpeg -nostdin -hide_banner -loglevel error -y -i "$work/f.png" -c:v libaom-av1 -still-picture 1 \
      -crf 30 -b:v 0 -cpu-used 4 -pix_fmt yuv420p "$OUT/$name-$w.avif" || rm -f "$OUT/$name-$w.avif"
  fi
done
printf '%s: %s (jpg %s)\n' "$name" "$(widths_of "$name" webp | paste -sd' ' -)" "$fallback"
build_manifest
